version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hierarchy_db
    restart: always
    environment:
      POSTGRES_USER: caian
      POSTGRES_PASSWORD: 3119
      POSTGRES_DB: hierarchy_management
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: